In [46]:
'''import requests
import os
import scipy.io as sio
import matplotlib.pyplot as plt
import numpy as np
import mne
from mne.io import RawArray

#Load the mat file of the first subjects training data
'''
'''Data - 
    - 2 sessions, 
    - 6 runs in each session, 
    - 12*4(=48) trials in each run,
    - 288 trials in each session.
    - 25 channels - (first 22 are EEG, last 3 are EOG) - need to remove those
    - cue onset classes and event type values: in training data 1, 2, 3, 4 -> 769, 770, 771, 772
    - trials containing artifacts as scored by experts are marked as events
      with the type 1023

#first subject, training session
#print(os.listdir())
##for py files, its in 'Notebook/...
file = sio.loadmat('A01T.mat')
#print(file)
#9 runs: 3 eog, 6 eeg
data = file['data'][0]

#remove the 3 first eog runs of each sesssion
data = data[3:]
data = data[0][0][0]

print(data[0])

##maybe provide list of the actual channel names(check: https://mne.tools/stable/auto_tutorials/simulation/10_array_objs.html#sphx-glr-auto-tutorials-simulation-10-array-objs-py)
# Extract necessary information
num_channels = 25  # Number of EEG channels - num_channels = len(data[0][0]) # Number of columns in the data matrix
sampling_freq = 250  # Sampling frequency -sampling_freq = data[3][0] # 250Hz

# Create MNE info instance
info = mne.create_info(num_channels, sfreq=sampling_freq, ch_types=['eeg']*22 + ['eog']*3)

print(info)
print(data[0].shape)
raw_array_1T = RawArray(data[0].T, info=info)
raw_array_1T.plot()
plt.show()'''

"Data - \n    - 2 sessions, \n    - 6 runs in each session, \n    - 12*4(=48) trials in each run,\n    - 288 trials in each session.\n    - 25 channels - (first 22 are EEG, last 3 are EOG) - need to remove those\n    - cue onset classes and event type values: in training data 1, 2, 3, 4 -> 769, 770, 771, 772\n    - trials containing artifacts as scored by experts are marked as events\n      with the type 1023\n\n#first subject, training session\n#print(os.listdir())\n##for py files, its in 'Notebook/...\nfile = sio.loadmat('A01T.mat')\n#print(file)\n#9 runs: 3 eog, 6 eeg\ndata = file['data'][0]\n\n#remove the 3 first eog runs of each sesssion\ndata = data[3:]\ndata = data[0][0][0]\n\nprint(data[0])\n\n##maybe provide list of the actual channel names(check: https://mne.tools/stable/auto_tutorials/simulation/10_array_objs.html#sphx-glr-auto-tutorials-simulation-10-array-objs-py)\n# Extract necessary information\nnum_channels = 25  # Number of EEG channels - num_channels = len(data[0][0])

In [47]:
#Rawarray
'''import scipy.io as sio
import matplotlib.pyplot as plt
import numpy as np
import mne
from mne.io import RawArray
from mne import EpochsArray, Epochs

# Load the mat file of the first subject's training data
file = sio.loadmat('A01T.mat')

# Extract EEG data
data = file['data'][0]

# Remove the first 3 EOG runs of each session
data = data[3:]
data = data[0][0][0]

# Extract necessary information
num_channels = 25  # Number of EEG channels
sampling_freq = 250  # Sampling frequency

# Create MNE info instance
info = mne.create_info(num_channels, sfreq=sampling_freq, ch_types=['eeg']*22 + ['eog']*3)

print(data[0].T)
print((data[0]).T.shape)
print(data[0][0][0].T)
time = (data[0].shape[0] / 250.0) 
# Assuming 250 Hz sampling frequency
# Create RawArray object and plot the data
##array for each trial and the concatenate? also need to add montage - electrode positions?
raw_array_1T = RawArray(data[0].T, info=info)
raw_array_1T.plot(events = data[0].T, n_channels = 25, duration= time, show_scrollbars=False, show_scalebars=False)
plt.show()

'''
'''
# Plot EEG data using matplotlib
# Plot EEG data using stacked plots
num_channels = len(data[0][0])
print(num_channels)
time = np.arange(data[0].shape[0] / 250.0)  # Assuming 250 Hz sampling frequency
print(time)

plt.figure(figsize=(12, 8))
for i in range(num_channels):
    plt.subplot(num_channels, 1, i+1)
    plt.plot(time, data[:, i])
    plt.title('EEG Channel {}'.format(i+1))
    plt.xlabel('Time (s)')
    plt.ylabel('Amplitude')
    plt.grid(True)

plt.tight_layout()
plt.show()
'''

"\n# Plot EEG data using matplotlib\n# Plot EEG data using stacked plots\nnum_channels = len(data[0][0])\nprint(num_channels)\ntime = np.arange(data[0].shape[0] / 250.0)  # Assuming 250 Hz sampling frequency\nprint(time)\n\nplt.figure(figsize=(12, 8))\nfor i in range(num_channels):\n    plt.subplot(num_channels, 1, i+1)\n    plt.plot(time, data[:, i])\n    plt.title('EEG Channel {}'.format(i+1))\n    plt.xlabel('Time (s)')\n    plt.ylabel('Amplitude')\n    plt.grid(True)\n\nplt.tight_layout()\nplt.show()\n"

In [48]:
'''#Epochs
import scipy.io as sio
from moabb.datasets import BNCI2014_001
import matplotlib.pyplot as plt
import numpy as np
import mne
from mne.io import RawArray
from mne import EpochsArray

# Load the mat file of the first subject's training data
file = sio.loadmat('A01T.mat')

# Extract EEG data for the first
data = file['data'][0]
# Remove the first 3 EOG runs of each session
data = data[3:]
data = data[0][0][0]

# Extract necessary information
num_channels = 25  # Number of EEG channels
sampling_freq = 250  # Sampling frequency

# Create MNE info instance
info = mne.create_info(num_channels, sfreq=sampling_freq, ch_types=['eeg']*22 + ['eog']*3)

print(data[0].T)
print((data[0]).T.shape)
print(data[0][0][0].T)
timeInTrial = (data[0].shape[0] / 250.0) /48
samplesInTrial = data[0].shape[0] // 48
print("samplesintrial:", samplesInTrial)
# Assuming 250 Hz sampling frequency

# Create RawArray objects and plot the data

##best way - find the event type markers - 769, 770,771,772 to identify exact cue onsets - were are they tho?, 
#then add 4 seconds(4 seconds are 1000 samples, 4*250Hz) to that time/sample to get t= 2 to t =6

##array for each trial and the concatenate? also need to add montage - electrode positions?

raw_array_1T = RawArray(data[0].T, info=info)

dataset = BNCI2014_001

subject_list = [1]
sessions = dataset.get_data(subject_list)
X, labels, meta = paradigm.get_data(dataset=dataset, subjects=subject_list)
epochs, labels, meta = paradigm.get_data(
    dataset=dataset, subjects=subject_list, return_epochs=True

start = 0
raw_arrays = []
for i in range(48):
    print("start:", start)
    end = (i+1) * samplesInTrial
    print("end", end)
    # Slice the data to ensure each slice has the same shape
    sliced_data = data[0][start:end].T
    raw_arrays.append(RawArray(sliced_data, info=info))
    start = end

event_labels = data[2]
print(event_labels) '''
#48 labels for the 48 trials in this first session

#epochs_arrays = EpochsArray(raw_arrays, info=info)
#epochs_arrays.plot(picks="misc", show_scrollbars=False, events=True)



'#Epochs\nimport scipy.io as sio\nfrom moabb.datasets import BNCI2014_001\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport mne\nfrom mne.io import RawArray\nfrom mne import EpochsArray\n\n# Load the mat file of the first subject\'s training data\nfile = sio.loadmat(\'A01T.mat\')\n\n# Extract EEG data for the first\ndata = file[\'data\'][0]\n# Remove the first 3 EOG runs of each session\ndata = data[3:]\ndata = data[0][0][0]\n\n# Extract necessary information\nnum_channels = 25  # Number of EEG channels\nsampling_freq = 250  # Sampling frequency\n\n# Create MNE info instance\ninfo = mne.create_info(num_channels, sfreq=sampling_freq, ch_types=[\'eeg\']*22 + [\'eog\']*3)\n\nprint(data[0].T)\nprint((data[0]).T.shape)\nprint(data[0][0][0].T)\ntimeInTrial = (data[0].shape[0] / 250.0) /48\nsamplesInTrial = data[0].shape[0] // 48\nprint("samplesintrial:", samplesInTrial)\n# Assuming 250 Hz sampling frequency\n\n# Create RawArray objects and plot the data\n\n##best way - find the ev

In [49]:

#using moabb to make the epochs

from moabb.datasets import BNCI2014_001
from moabb.evaluations import CrossSessionEvaluation
from moabb.paradigms import MotorImagery

import matplotlib.pyplot as plt
import numpy as np

import mne
from mne.io import RawArray
from mne import EpochsArray

#loading the dataset

dataset = BNCI2014_001()
dataset.subject_list = dataset.subject_list[:3] 
print("Subject_list_dataset: \n",dataset.subject_list)
print("\n")
datasets = [dataset]
paradigm =MotorImagery()

#Get the data as MNE epochs
subject_list = [1]
sessions = dataset.get_data(subject_list)
print("Sessions: \n")
for i in sessions:
    print(i)
    print("\n")
print("Sessions: \n",sessions)
print("\n")

'''#this returns numpy array
X, labels, meta = paradigm.get_data(dataset=dataset, subjects=subject_list)'''

#This returns epochs as its set to true
epochs, labels, meta = paradigm.get_data(
    dataset=dataset, subjects=subject_list, return_epochs=True
)
print("epochs: \n", epochs)
print("\n")
print("labels: \n", labels)
print("\n")
print("labeles_length: \n", len(labels))


'''start = 0
raw_arrays = []
for i in range(48):
    print("start:", start)
    end = (i+1) * samplesInTrial
    print("end", end)
    # Slice the data to ensure each slice has the same shape
    sliced_data = data[0][start:end].T
    raw_arrays.append(RawArray(sliced_data, info=info))
    start = end

event_labels = data[2]
print(event_labels) '''
#48 labels for the 48 trials in this first session

#epochs_arrays = EpochsArray(raw_arrays, info=info)
#epochs_arrays.plot(picks="misc", show_scrollbars=False, events=True)



Choosing from all possible events


Subject_list_dataset: 
 [1, 2, 3]


Sessions: 

1


Sessions: 
 {1: {'0train': {'0': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '1': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '2': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '3': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '4': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '5': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>}, '1test': {'0': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '1': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '2': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '3': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '4': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '5': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>}}}


Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 co

c:\Users\Eier\miniconda3\envs\mne\Lib\site-packages\moabb\paradigms\base.py:354: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  X = mne.concatenate_epochs(X)


'start = 0\nraw_arrays = []\nfor i in range(48):\n    print("start:", start)\n    end = (i+1) * samplesInTrial\n    print("end", end)\n    # Slice the data to ensure each slice has the same shape\n    sliced_data = data[0][start:end].T\n    raw_arrays.append(RawArray(sliced_data, info=info))\n    start = end\n\nevent_labels = data[2]\nprint(event_labels) '

In [50]:
'''#Epochs
import scipy.io as sio
from moabb.datasets import BNCI2014_001
import matplotlib.pyplot as plt
import numpy as np
import mne
from mne.io import RawArray
from mne import EpochsArray

# Load the mat file of the first subject's training data
file = sio.loadmat('A01T.mat')

# Extract EEG data for the first
data = file['data'][0]
# Remove the first 3 EOG runs of each session
data = data[3:]
data = data[0][0][0]

# Extract necessary information
num_channels = 25  # Number of EEG channels
sampling_freq = 250  # Sampling frequency

# Create MNE info instance
info = mne.create_info(num_channels, sfreq=sampling_freq, ch_types=['eeg']*22 + ['eog']*3)

print(data[0].T)
print((data[0]).T.shape)
print(data[0][0][0].T)
timeInTrial = (data[0].shape[0] / 250.0) /48
samplesInTrial = data[0].shape[0] // 48
print("samplesintrial:", samplesInTrial)
# Assuming 250 Hz sampling frequency

# Create RawArray objects and plot the data

##best way - find the event type markers - 769, 770,771,772 to identify exact cue onsets - were are they tho?, 
#then add 4 seconds(4 seconds are 1000 samples, 4*250Hz) to that time/sample to get t= 2 to t =6

##array for each trial and the concatenate? also need to add montage - electrode positions?

raw_array_1T = RawArray(data[0].T, info=info)

dataset = BNCI2014_001

subject_list = [1]
sessions = dataset.get_data(subject_list)
X, labels, meta = paradigm.get_data(dataset=dataset, subjects=subject_list)
epochs, labels, meta = paradigm.get_data(
    dataset=dataset, subjects=subject_list, return_epochs=True
'''
'''start = 0
raw_arrays = []
for i in range(48):
    print("start:", start)
    end = (i+1) * samplesInTrial
    print("end", end)
    # Slice the data to ensure each slice has the same shape
    sliced_data = data[0][start:end].T
    raw_arrays.append(RawArray(sliced_data, info=info))
    start = end

event_labels = data[2]
print(event_labels) '''
#48 labels for the 48 trials in this first session

#epochs_arrays = EpochsArray(raw_arrays, info=info)
#epochs_arrays.plot(picks="misc", show_scrollbars=False, events=True)



'start = 0\nraw_arrays = []\nfor i in range(48):\n    print("start:", start)\n    end = (i+1) * samplesInTrial\n    print("end", end)\n    # Slice the data to ensure each slice has the same shape\n    sliced_data = data[0][start:end].T\n    raw_arrays.append(RawArray(sliced_data, info=info))\n    start = end\n\nevent_labels = data[2]\nprint(event_labels) '

In [51]:
'''#Epochs
import scipy.io as sio
from moabb.datasets import BNCI2014_001
import matplotlib.pyplot as plt
import numpy as np
import mne
from mne.io import RawArray
from mne import EpochsArray

# Load the mat file of the first subject's training data
file = sio.loadmat('A01T.mat')

# Extract EEG data for the first
data = file['data'][0]
# Remove the first 3 EOG runs of each session
data = data[3:]
data = data[0][0][0]

# Extract necessary information
num_channels = 25  # Number of EEG channels
sampling_freq = 250  # Sampling frequency

# Create MNE info instance
info = mne.create_info(num_channels, sfreq=sampling_freq, ch_types=['eeg']*22 + ['eog']*3)

print(data[0].T)
print((data[0]).T.shape)
print(data[0][0][0].T)
timeInTrial = (data[0].shape[0] / 250.0) /48
samplesInTrial = data[0].shape[0] // 48
print("samplesintrial:", samplesInTrial)
# Assuming 250 Hz sampling frequency

# Create RawArray objects and plot the data

##best way - find the event type markers - 769, 770,771,772 to identify exact cue onsets - were are they tho?, 
#then add 4 seconds(4 seconds are 1000 samples, 4*250Hz) to that time/sample to get t= 2 to t =6

##array for each trial and the concatenate? also need to add montage - electrode positions?

raw_array_1T = RawArray(data[0].T, info=info)

dataset = BNCI2014_001

subject_list = [1]
sessions = dataset.get_data(subject_list)
X, labels, meta = paradigm.get_data(dataset=dataset, subjects=subject_list)
epochs, labels, meta = paradigm.get_data(
    dataset=dataset, subjects=subject_list, return_epochs=True

start = 0
raw_arrays = []
for i in range(48):
    print("start:", start)
    end = (i+1) * samplesInTrial
    print("end", end)
    # Slice the data to ensure each slice has the same shape
    sliced_data = data[0][start:end].T
    raw_arrays.append(RawArray(sliced_data, info=info))
    start = end

event_labels = data[2]
print(event_labels) '''
#48 labels for the 48 trials in this first session

#epochs_arrays = EpochsArray(raw_arrays, info=info)
#epochs_arrays.plot(picks="misc", show_scrollbars=False, events=True)



'#Epochs\nimport scipy.io as sio\nfrom moabb.datasets import BNCI2014_001\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport mne\nfrom mne.io import RawArray\nfrom mne import EpochsArray\n\n# Load the mat file of the first subject\'s training data\nfile = sio.loadmat(\'A01T.mat\')\n\n# Extract EEG data for the first\ndata = file[\'data\'][0]\n# Remove the first 3 EOG runs of each session\ndata = data[3:]\ndata = data[0][0][0]\n\n# Extract necessary information\nnum_channels = 25  # Number of EEG channels\nsampling_freq = 250  # Sampling frequency\n\n# Create MNE info instance\ninfo = mne.create_info(num_channels, sfreq=sampling_freq, ch_types=[\'eeg\']*22 + [\'eog\']*3)\n\nprint(data[0].T)\nprint((data[0]).T.shape)\nprint(data[0][0][0].T)\ntimeInTrial = (data[0].shape[0] / 250.0) /48\nsamplesInTrial = data[0].shape[0] // 48\nprint("samplesintrial:", samplesInTrial)\n# Assuming 250 Hz sampling frequency\n\n# Create RawArray objects and plot the data\n\n##best way - find the ev

In [52]:
from moabb.analysis.plotting import paired_plot, summary_plot
from moabb.datasets import BNCI2014_001
from moabb.evaluations import CrossSessionEvaluation
from moabb.paradigms import MotorImagery

dataset = BNCI2014_001()
#dataset.subject_list = dataset.subject_list[:3]
datasets = [dataset]
paradigm = MotorImagery()

subject_list = [1]
sessions = dataset.get_data(subject_list)
#returns mne epochs 



Choosing from all possible events


Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
576 matching events found
No baseline correction applied


c:\Users\Eier\miniconda3\envs\mne\Lib\site-packages\moabb\paradigms\base.py:354: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  X = mne.concatenate_epochs(X)


In [66]:
epochs, labels, meta = paradigm.get_data(
    dataset=dataset, subjects=subject_list, return_epochs=True
)

print(sessions[1]["0train"])
print("\n")
print(sessions[1]["1test"])
print("\n")

print(epochs.events)
print(epochs.event_id)
print(epochs.tmin, epochs.tmax)
print(epochs)


Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
Adding metadata with 3 columns
576 matching events found
No baseline correction applied
{'0': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '1': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '2': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '3': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '4': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '5': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>}


{'0': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '1': <RawArray | 26 x 96735 (386.9 s), ~19.2 MB, data loaded>, '2': <RawArray | 26 x 96735 (386

c:\Users\Eier\miniconda3\envs\mne\Lib\site-packages\moabb\paradigms\base.py:354: RuntimeWarning: Concatenation of Annotations within Epochs is not supported yet. All annotations will be dropped.
  X = mne.concatenate_epochs(X)


In [71]:
print("events ", epochs.events)


events  [[    250       0       4]
 [   2253       0       3]
 [   4171       0       2]
 ...
 [1176911       0       3]
 [1179025       0       1]
 [1181084       0       3]]


In [76]:
import numpy as np

print("before: ", epochs.events)
labels = epochs.events[:, -1] -4
print("lables after: ", labels)

class_balance = np.zeros(4)
for i in range(4):
    class_balance[i] = np.mean(labels == i)
print(class_balance)
class_balance = np.max(class_balance)


before:  [[    250       0       4]
 [   2253       0       3]
 [   4171       0       2]
 ...
 [1176911       0       3]
 [1179025       0       1]
 [1181084       0       3]]
lables after:  [ 0 -1 -2 -3 -3 -2 -1  0 -2 -1 -3 -3 -3  0 -2 -2 -3 -3 -1 -3 -2  0  0 -1
 -3  0  0 -2  0  0 -2 -3 -2 -1 -1 -1  0 -1 -3  0 -2 -1 -2 -1  0 -2 -1 -3
 -3 -3  0 -2 -3 -1 -3 -1 -2  0 -3 -1 -1 -3 -1 -2  0  0  0 -1 -3  0 -2  0
 -2 -3 -1 -2 -3 -1 -1 -3 -1  0  0 -2 -3 -2  0 -2  0 -1 -2 -2 -2 -1  0 -3
 -2  0 -3 -1 -1  0 -3 -3 -1 -2  0  0  0 -2 -3 -1 -2  0 -3  0 -1 -2  0  0
 -3 -2 -2 -1  0 -2 -3 -3  0 -2 -3 -1 -2 -2 -1 -3  0 -1 -1 -1 -1 -3 -2 -3
 -2 -3 -3 -1 -1 -2 -1  0 -3  0 -3 -3 -2  0 -1 -2  0 -1  0 -1  0 -2 -2  0
 -3 -2 -2 -2 -1  0 -3  0 -3 -1 -3  0 -3 -1 -3 -2 -1 -1  0 -3 -2  0 -2 -1
 -1 -3  0 -2  0 -3 -3 -1 -1 -2  0 -2 -2 -3 -2  0  0 -2 -2 -2 -2  0  0 -1
  0 -3 -2 -1 -2 -3  0 -3  0 -3 -3 -3 -3 -1 -1  0 -2 -1 -1 -1  0 -1 -3 -1
 -3  0 -2  0  0 -1  0  0 -1 -2  0 -1 -3 -2 -2 -2 -1 -2  0 -1  0 -2 -1 -3
  0 -

In [79]:
epochs_data =epochs.get_data(copy=False)
epochs_data

array([[[ 5.52359238e-06,  6.05479173e-06,  5.55222300e-06, ...,
         -5.72856071e-07, -2.82827100e-06, -5.00875118e-06],
        [ 1.91658213e-06,  1.74039129e-06,  8.80343196e-07, ...,
          5.06184938e-07, -3.31466548e-06, -6.65938125e-06],
        [ 3.41951163e-06,  3.84870584e-06,  3.50987378e-06, ...,
         -1.52997242e-06, -5.09625352e-06, -7.88780877e-06],
        ...,
        [-1.18565960e-06, -1.51034610e-06, -2.41203985e-06, ...,
         -2.33472371e-06, -6.69460626e-06, -9.35521896e-06],
        [-2.35736743e-06, -3.05259983e-06, -3.87318513e-06, ...,
         -2.61970359e-06, -6.21065549e-06, -8.26673539e-06],
        [-1.09144736e-06, -1.01641231e-06, -1.73219282e-06, ...,
          6.21774064e-08, -3.33972413e-06, -5.84536201e-06]],

       [[-5.94328262e-06, -5.49236729e-06, -3.71652245e-06, ...,
          9.71111097e-06,  8.34966036e-06,  5.93386064e-06],
        [-6.39517030e-06, -6.41812583e-06, -4.88865165e-06, ...,
          7.27015452e-06,  6.35452504e